version: "3"

services:
  app:
    user: $UID:$GID
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python3 manage.py runserver 0.0.0.0:8000